[package]
name = "textractor-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name="textractor"
path="src/main.rs"

[dependencies]
anyhow = "1.0.82"
clap = "4.5.4"
textractor = { path = "../textractor-core"}
